### ISSUE TITLE
Remove Upper Bound for compatibility limit

### ISSUE THREAD

**Issue by simschla** [ragurney/spotless-intellij-gradle#43]
Whenever I update intellij, spotless-intellij-gradle plugin is one of the few plugins, that is not compatible until a new version is released.

This is probably due to the upper bound limit here, if I read the code correctly:

https://github.com/ragurney/spotless-intellij-gradle/blob/51fe46ead8e1c536f638d3416a63a8e1b86421cb/build.gradle.kts#L70

I suggest to remove this upper bound, since the plugin uses only a small section of Intellij's api and therefore the plugin is not likely to break when a new Intellij version is released.

(Currently, it ALWAYS breaks whenever a new Intellij version is released)

**Comment by mikewacker** [comment]
+1, I get this error when I start IntelliJ IDEA 2022.3

> Plugin 'Spotless Gradle' (version '1.0.8') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is IC-223.7571.182

I'm on Ubuntu 22.04 LTS and installed the IntelliJ IDEA via `snap`; it recently upgraded me from 2022.2 to 2022.3.

**Comment by ragurney** [comment]
Thanks for reporting @simschla. As you allude to, I left the `untilBuild` due to an abundance of caution not wanting to break on newer versions, though as you say that's probably very unlikely. 

Given that this has been main pain point of this plugin so far, I'm willing to remove the upper bound and see how it goes.
